### PR TITLE
Create mail function in utils.py file

### LINKED ISSUE #26: Email Feature
Create **utility.py** in **api directory** and implement:

- send_email function

Also implement sending an email when a **Patient** or **Health Officer** account is created.

### PR DESCRIPTION
**Pull request by blacdev**

### CODE REVIEW

**Review by austinoski — COMMENTED** [review]
What type is the *request* argument and what is the content?

**Comment by austinoski** [comment]
Inconsistent function naming *json_confirmed* and *mail_Function*. All should be lower case.

Bad function name *mail_Function*

**Comment by austinoski** [comment]
Filename should be lower case like *utils.py* not *Utils.py*.

**Comment by blacdev** [comment]
okay. Will make corrections now

**Pull request closed without merging**
